/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package applicationconfiguration;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author home
 */
public class Config extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement prepareStatement = null;
    ResultSet resultSet = null;
    Statement statement;

    public Config() {
        initComponents();
        showConfigTableData();
        showSummaryTableData();
        showModuleTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        url_TextField = new javax.swing.JTextField();
        Browser_ComboBox = new javax.swing.JComboBox<>();
        AppName_TextField = new javax.swing.JTextField();
        inputMethod_ComboBox = new javax.swing.JComboBox<>();
        dbConnectionFlag_ComboBox = new javax.swing.JComboBox<>();
        waitTime_TextField = new javax.swing.JTextField();
        authenticationWindow_TextField = new javax.swing.JTextField();
        authenticationWindowPresent_ComboBox = new javax.swing.JComboBox<>();
        Language_ComboBox = new javax.swing.JComboBox<>();
        dbDriver_TextField = new javax.swing.JTextField();
        dbHost_TextField = new javax.swing.JTextField();
        dbPassword_TextField = new javax.swing.JPasswordField();
        dbUser = new javax.swing.JTextField();
        FailRunIteration_TextField = new javax.swing.JTextField();
        noOfTestData_TextField = new javax.swing.JTextField();
        AddConfigBtn = new javax.swing.JButton();
        UpdateConfigBtn = new javax.swing.JButton();
        HomeConfigBtn = new javax.swing.JButton();
        SignOutConfigBtn = new javax.swing.JButton();
        ClearConfigBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Domain_TextField = new javax.swing.JTextField();
        SubDomain_TextField = new javax.swing.JTextField();
        Project_TextField = new javax.swing.JTextField();
        Type_TextField = new javax.swing.JTextField();
        Environment_TextField = new javax.swing.JTextField();
        Language_TextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Summary_Table = new javax.swing.JTable();
        lMessageSummary = new javax.swing.JLabel();
        AddSummaryBtn = new javax.swing.JButton();
        UpdateSummaryBtn = new javax.swing.JButton();
        ClearSummaryBtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Module_Table = new javax.swing.JTable();
        lMessageModule = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        ModuleNo_TextField = new javax.swing.JTextField();
        AddModuleBtn = new javax.swing.JButton();
        UpdateModuleBtn = new javax.swing.JButton();
        DeleteModuleBtn = new javax.swing.JButton();
        ModuleName_TextField = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Config_Table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Configuration", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 18), new java.awt.Color(0, 0, 153))); // NOI18N

        jLabel9.setText("URL:");

        jLabel12.setText("Browser:");

        jLabel13.setText("appName:");

        jLabel14.setText("iinputMethod:");

        jLabel15.setText("dbConnectionFlag:");

        jLabel16.setText("waitTime:");

        jLabel17.setText("authenticationWindow:");

        jLabel18.setText("authenticationWindowPresent:");

        jLabel19.setText("Language:");

        jLabel20.setText("dbDriver:");

        jLabel21.setText("dbHost:");

        jLabel22.setText("dbUser:");

        jLabel23.setText("dbPassword:");

        jLabel24.setText("FailRunIteration:");

        jLabel25.setText("noOfTestData:");

        Browser_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chrome", "IE", "Firefox" }));
        Browser_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Browser_ComboBoxActionPerformed(evt);
            }
        });

        inputMethod_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manual", "System" }));

        dbConnectionFlag_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));

        authenticationWindowPresent_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));

        Language_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "English", "French" }));

        dbPassword_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbPassword_TextFieldActionPerformed(evt);
            }
        });

        AddConfigBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Button-Add-icon.png"))); // NOI18N
        AddConfigBtn.setText("Add");
        AddConfigBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddConfigBtnActionPerformed(evt);
            }
        });

        UpdateConfigBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Files-Edit-file-icon (1).png"))); // NOI18N
        UpdateConfigBtn.setText("Update");
        UpdateConfigBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateConfigBtnActionPerformed(evt);
            }
        });

        HomeConfigBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        HomeConfigBtn.setText("Home");
        HomeConfigBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeConfigBtnActionPerformed(evt);
            }
        });

        SignOutConfigBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SignOut-icon (1).png"))); // NOI18N
        SignOutConfigBtn.setText("SignOut");
        SignOutConfigBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignOutConfigBtnActionPerformed(evt);
            }
        });

        ClearConfigBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Actions-edit-clear-icon (1).png"))); // NOI18N
        ClearConfigBtn.setText("Clear");
        ClearConfigBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearConfigBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dbHost_TextField)
                            .addComponent(dbDriver_TextField)
                            .addComponent(dbUser)
                            .addComponent(dbPassword_TextField)
                            .addComponent(FailRunIteration_TextField)
                            .addComponent(inputMethod_ComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dbConnectionFlag_ComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(waitTime_TextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(authenticationWindow_TextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Language_ComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(authenticationWindowPresent_ComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AppName_TextField)
                            .addComponent(Browser_ComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(url_TextField)
                            .addComponent(noOfTestData_TextField, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(AddConfigBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(UpdateConfigBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ClearConfigBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(HomeConfigBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SignOutConfigBtn)
                        .addGap(0, 10, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(url_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(Browser_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(AppName_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(inputMethod_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(dbConnectionFlag_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(waitTime_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(authenticationWindow_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(authenticationWindowPresent_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(Language_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(dbDriver_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(dbHost_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(dbUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(dbPassword_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(FailRunIteration_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(noOfTestData_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddConfigBtn)
                    .addComponent(UpdateConfigBtn)
                    .addComponent(HomeConfigBtn)
                    .addComponent(SignOutConfigBtn)
                    .addComponent(ClearConfigBtn))
                .addGap(24, 24, 24))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Summary", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 18), new java.awt.Color(0, 0, 153))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Label");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Value");

        jLabel3.setText("Domain:");

        jLabel4.setText("Sub Domain:");

        jLabel5.setText("Project:");

        jLabel6.setText("Type:");

        jLabel7.setText("Environment:");

        jLabel8.setText("Language:");

        Summary_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Domain", "Sun Domain", "Project", "Type", "Environment", "Language"
            }
        ));
        Summary_Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Summary_TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Summary_Table);

        lMessageSummary.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N
        lMessageSummary.setForeground(new java.awt.Color(255, 0, 0));

        AddSummaryBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Button-Add-icon.png"))); // NOI18N
        AddSummaryBtn.setText("Add");
        AddSummaryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddSummaryBtnActionPerformed(evt);
            }
        });

        UpdateSummaryBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Files-Edit-file-icon (1).png"))); // NOI18N
        UpdateSummaryBtn.setText("Update");
        UpdateSummaryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateSummaryBtnActionPerformed(evt);
            }
        });

        ClearSummaryBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Actions-edit-clear-icon (1).png"))); // NOI18N
        ClearSummaryBtn.setText("Clear");
        ClearSummaryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearSummaryBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lMessageSummary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Domain_TextField)
                                    .addComponent(SubDomain_TextField)
                                    .addComponent(Project_TextField)
                                    .addComponent(Type_TextField)
                                    .addComponent(Environment_TextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Language_TextField))))))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(UpdateSummaryBtn)
                .addGap(18, 18, 18)
                .addComponent(AddSummaryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ClearSummaryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Domain_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(SubDomain_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Project_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(Type_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Environment_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Language_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lMessageSummary, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddSummaryBtn)
                    .addComponent(UpdateSummaryBtn)
                    .addComponent(ClearSummaryBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Modules", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 18), new java.awt.Color(0, 0, 153))); // NOI18N

        Module_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Module No.", "Module Name"
            }
        ));
        Module_Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Module_TableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(Module_Table);

        lMessageModule.setForeground(new java.awt.Color(255, 0, 0));

        jLabel10.setText("Module No.");

        jLabel11.setText("Module Name:");

        AddModuleBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Button-Add-icon.png"))); // NOI18N
        AddModuleBtn.setText("Add");
        AddModuleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddModuleBtnActionPerformed(evt);
            }
        });

        UpdateModuleBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Files-Edit-file-icon (1).png"))); // NOI18N
        UpdateModuleBtn.setText("Update");
        UpdateModuleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateModuleBtnActionPerformed(evt);
            }
        });

        DeleteModuleBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bin-2-icon.png"))); // NOI18N
        DeleteModuleBtn.setText("Delete");
        DeleteModuleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteModuleBtnActionPerformed(evt);
            }
        });

        ModuleName_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModuleName_TextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(UpdateModuleBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(AddModuleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DeleteModuleBtn))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lMessageModule, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ModuleNo_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ModuleName_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(ModuleNo_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(ModuleName_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(lMessageModule, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(UpdateModuleBtn)
                        .addComponent(AddModuleBtn))
                    .addComponent(DeleteModuleBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Config_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "URL", "Browser", "AppName", "inputMethod", "dbConnectionFlag", "waitFor", "authenticationWindow", "authenticationWindowPresent", "language", "dbDriver", "dbHost", "dbUser", "dbPassword", "FailRunIteration", "noOfTestData"
            }
        ));
        Config_Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Config_TableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Config_Table);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1221, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 74, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        setBounds(0, 0, 1255, 738);
    }// </editor-fold>//GEN-END:initComponents

    private void ModuleName_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModuleName_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModuleName_TextFieldActionPerformed

    private void dbPassword_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbPassword_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dbPassword_TextFieldActionPerformed

    private void Browser_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Browser_ComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Browser_ComboBoxActionPerformed
    public void addConfigIntoDatabase() {
        try {
            con = MySQLConnection.getConnection();

            //Write a query to insert data into database
            String insertData = "insert into config(url,browser,appName,inputMethod,deConnectionFlag,waitfor,autoITPath,autoITFlag,language,deDriver,dbHost,dbUser,dbPass,failRunIteration,noOfTestData) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";

            prepareStatement = con.prepareStatement(insertData);
            prepareStatement.setString(1, url_TextField.getText());
            prepareStatement.setString(2, Browser_ComboBox.getSelectedItem().toString());
            prepareStatement.setString(3, AppName_TextField.getText());
            prepareStatement.setString(4, inputMethod_ComboBox.getSelectedItem().toString());
            prepareStatement.setString(5, dbConnectionFlag_ComboBox.getSelectedItem().toString());
            prepareStatement.setString(6, waitTime_TextField.getText());
            prepareStatement.setString(7, authenticationWindow_TextField.getText());
            prepareStatement.setString(8, authenticationWindowPresent_ComboBox.getSelectedItem().toString());
            prepareStatement.setString(9, Language_ComboBox.getSelectedItem().toString());
            prepareStatement.setString(10, dbDriver_TextField.getText());
            prepareStatement.setString(11, dbHost_TextField.getText());
            prepareStatement.setString(12, dbUser.getText());
            prepareStatement.setString(13, dbPassword_TextField.getText());
            prepareStatement.setString(14, FailRunIteration_TextField.getText());
            prepareStatement.setString(15, noOfTestData_TextField.getText());

            if (!url_TextField.getText().equals("")) {
                prepareStatement.execute();
                lMessageSummary.setText("Data added successfully");
            } else {
                JOptionPane.showMessageDialog(null, "insufficent informations");
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        } finally {
            try {
                con.close();
                prepareStatement.close();
                resultSet.close();
            } catch (Exception e) {

            }
        }
    }

    public void showConfigTableData() {
        try {
            con = MySQLConnection.getConnection();
            String query = "select * from config";
            prepareStatement = con.prepareStatement(query);
            resultSet = prepareStatement.executeQuery();
            Config_Table.setModel(DbUtils.resultSetToTableModel(resultSet));
        } catch (Exception e) {
            System.out.println("Unable to featch Data from database");
            JOptionPane.showMessageDialog(null, "Unable to featch Data from database");
        } finally {
            try {
                con.close();
                prepareStatement.close();
                resultSet.close();
            } catch (Exception e) {

            }
        }
    }


    private void AddConfigBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddConfigBtnActionPerformed
        try {
            addConfigIntoDatabase();
            showConfigTableData();
        } catch (Exception e) {

        }
    }//GEN-LAST:event_AddConfigBtnActionPerformed

    private void Config_TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Config_TableMouseClicked
        DefaultTableModel model = (DefaultTableModel) Config_Table.getModel();
        url_TextField.setText(model.getValueAt(Config_Table.getSelectedRow(), 0).toString());
        Browser_ComboBox.setSelectedItem(model.getValueAt(Config_Table.getSelectedRow(), 1).toString());
        AppName_TextField.setText(model.getValueAt(Config_Table.getSelectedRow(), 2).toString());
        inputMethod_ComboBox.setSelectedItem(model.getValueAt(Config_Table.getSelectedRow(), 3).toString());
        dbConnectionFlag_ComboBox.setSelectedItem(model.getValueAt(Config_Table.getSelectedRow(), 4).toString());
        waitTime_TextField.setText(model.getValueAt(Config_Table.getSelectedRow(), 5).toString());
        authenticationWindow_TextField.setText(model.getValueAt(Config_Table.getSelectedRow(), 6).toString());
        authenticationWindowPresent_ComboBox.setSelectedItem(model.getValueAt(Config_Table.getSelectedRow(), 7).toString());
        Language_ComboBox.setSelectedItem(model.getValueAt(Config_Table.getSelectedRow(), 8).toString());
        dbDriver_TextField.setText(model.getValueAt(Config_Table.getSelectedRow(), 9).toString());
        dbHost_TextField.setText(model.getValueAt(Config_Table.getSelectedRow(), 10).toString());
        dbUser.setText(model.getValueAt(Config_Table.getSelectedRow(), 11).toString());
        dbPassword_TextField.setText(model.getValueAt(Config_Table.getSelectedRow(), 12).toString());
        FailRunIteration_TextField.setText(model.getValueAt(Config_Table.getSelectedRow(), 13).toString());
        noOfTestData_TextField.setText(model.getValueAt(Config_Table.getSelectedRow(), 14).toString());


    }//GEN-LAST:event_Config_TableMouseClicked

    private void UpdateConfigBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateConfigBtnActionPerformed
        try {
            lMessageSummary.setText("");
            DefaultTableModel model = (DefaultTableModel) Config_Table.getModel();
            if (Config_Table.getSelectedRow() == -1) {
                if (Config_Table.getRowCount() == 0) {
                    lMessageSummary.setText("Table is empty");
                } else {
                    lMessageSummary.setText("You must select a record");
                }
            } else {

                con = MySQLConnection.getConnection();

                String url = url_TextField.getText();
                String browser = Browser_ComboBox.getSelectedItem().toString();
                String appName = AppName_TextField.getText();
                String inputMethod = inputMethod_ComboBox.getSelectedItem().toString();
                String dbConnectionFlag = dbConnectionFlag_ComboBox.getSelectedItem().toString();
                String waitTime = waitTime_TextField.getText();
                String authenticationWindow = authenticationWindow_TextField.getText();
                String authenticationWindowPresent = authenticationWindowPresent_ComboBox.getSelectedItem().toString();
                String language = Language_ComboBox.getSelectedItem().toString();
                String dbDriver = dbDriver_TextField.getText();
                String dbHost = dbHost_TextField.getText();
                String dbUsername = dbUser.getText();
                String dbPass = dbPassword_TextField.getText();
                String FailRunIteration = FailRunIteration_TextField.getText();
                String noOfTestData = noOfTestData_TextField.getText();

                String updateQuery = "update config set url = '" + url + "', browser= '" + browser + "', appName= '" + appName + "', inputMethod= '" + inputMethod + "', deConnectionFlag= '" + dbConnectionFlag + "', waitfor= '" + waitTime + "', autoITPath= '" + authenticationWindow + "', autoITFlag= '" + authenticationWindowPresent + "', language= '" + language + "', deDriver= '" + dbDriver + "', deDriver= '" + dbHost + "', dbUser= '" + dbUsername + "', dbPass= '" + dbPass + "', failRunIteration= '" + FailRunIteration + "', noOfTestData= '" + noOfTestData + "'";

                statement = con.createStatement();

                statement.executeUpdate(updateQuery);

                this.showConfigTableData();

                lMessageSummary.setText("Data updated successfully");
            }
        } catch (Exception e) {
            lMessageSummary.setText("Somthing went wrong while updating table data");
        } finally {
            try {
                con.close();
                prepareStatement.close();
            } catch (Exception e) {

            }
        }
    }//GEN-LAST:event_UpdateConfigBtnActionPerformed

    private void HomeConfigBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeConfigBtnActionPerformed
        try {
            close();
            new HomePage().setVisible(true);
        } catch (Exception e) {

        }
    }//GEN-LAST:event_HomeConfigBtnActionPerformed

    private void SignOutConfigBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignOutConfigBtnActionPerformed
        try {
            close();
            new login().setVisible(true);
        } catch (Exception e) {

        }
    }//GEN-LAST:event_SignOutConfigBtnActionPerformed

    public void close() {

        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);

    }
    private void ClearConfigBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearConfigBtnActionPerformed
        url_TextField.setText("");
        Browser_ComboBox.setSelectedItem("IE");
        AppName_TextField.setText("");
        inputMethod_ComboBox.setSelectedItem("Manual");
        dbConnectionFlag_ComboBox.setSelectedItem("No");
        waitTime_TextField.setText("");
        authenticationWindow_TextField.setText("");
        authenticationWindowPresent_ComboBox.setSelectedItem("No");
        Language_ComboBox.setSelectedItem("English");
        dbDriver_TextField.setText("");
        dbHost_TextField.setText("");
        dbUser.setText("");
        dbPassword_TextField.setText("");
        FailRunIteration_TextField.setText("");
        noOfTestData_TextField.setText("");
    }//GEN-LAST:event_ClearConfigBtnActionPerformed

    private void AddModuleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddModuleBtnActionPerformed
        try {
            con = MySQLConnection.getConnection();

            //Write a query to insert data into database
            String insertData = "insert into moduledetails(ModuleNo,moduleName) values(?,?)";

            prepareStatement = con.prepareStatement(insertData);
            prepareStatement.setString(1, ModuleNo_TextField.getText());
            prepareStatement.setString(2, ModuleName_TextField.getText());
            if (!ModuleName_TextField.getText().equals("")) {
                prepareStatement.execute();
                lMessageModule.setText("Data added successfully");
                showModuleTableData();
            } else {
                JOptionPane.showMessageDialog(null, "insufficent informations");
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        } finally {
            try {
                con.close();
                prepareStatement.close();
                resultSet.close();
            } catch (Exception e) {

            }
        }
    }//GEN-LAST:event_AddModuleBtnActionPerformed

    private void AddSummaryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddSummaryBtnActionPerformed
        try {
            con = MySQLConnection.getConnection();

            //Write a query to insert data into database
            String insertData = "insert into summarydetails(domain,subDomain,project,type,environment,Language) values(?,?,?,?,?,?)";

            prepareStatement = con.prepareStatement(insertData);
            prepareStatement.setString(1, Domain_TextField.getText());
            prepareStatement.setString(2, SubDomain_TextField.getText());
            prepareStatement.setString(3, Project_TextField.getText());
            prepareStatement.setString(4, Type_TextField.getText());
            prepareStatement.setString(5, Environment_TextField.getText());
            prepareStatement.setString(6, Language_TextField.getText());
            if (!Project_TextField.getText().equals("")) {
                prepareStatement.execute();
                lMessageSummary.setText("Data added successfully");
                showSummaryTableData();
            } else {
                JOptionPane.showMessageDialog(null, "insufficent informations");
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        } finally {
            try {
                con.close();
                prepareStatement.close();
                resultSet.close();
            } catch (Exception e) {

            }
        }
    }//GEN-LAST:event_AddSummaryBtnActionPerformed

    private void ClearSummaryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearSummaryBtnActionPerformed
        Domain_TextField.setText("");
        SubDomain_TextField.setText("");
        Project_TextField.setText("");
        Type_TextField.setText("");
        Environment_TextField.setText("");
        Language_TextField.setText("");
    }//GEN-LAST:event_ClearSummaryBtnActionPerformed

    private void Summary_TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Summary_TableMouseClicked
        DefaultTableModel model = (DefaultTableModel) Summary_Table.getModel();
        Domain_TextField.setText(model.getValueAt(Summary_Table.getSelectedRow(), 0).toString());
        SubDomain_TextField.setText(model.getValueAt(Summary_Table.getSelectedRow(), 1).toString());
        Project_TextField.setText(model.getValueAt(Summary_Table.getSelectedRow(), 2).toString());
        Type_TextField.setText(model.getValueAt(Summary_Table.getSelectedRow(), 3).toString());
        Environment_TextField.setText(model.getValueAt(Summary_Table.getSelectedRow(), 4).toString());
        Language_TextField.setText(model.getValueAt(Summary_Table.getSelectedRow(), 5).toString());

    }//GEN-LAST:event_Summary_TableMouseClicked

    private void UpdateSummaryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateSummaryBtnActionPerformed
        try {
            lMessageSummary.setText("");
            DefaultTableModel model = (DefaultTableModel) Summary_Table.getModel();
            if (Summary_Table.getSelectedRow() == -1) {
                if (Summary_Table.getRowCount() == 0) {
                    lMessageSummary.setText("Table is empty");
                } else {
                    lMessageSummary.setText("You must select a record");
                }
            } else {

                con = MySQLConnection.getConnection();

                String domain = Domain_TextField.getText();
                String subDomain = SubDomain_TextField.getText();
                String project = Project_TextField.getText();
                String type = Type_TextField.getText();
                String environment = Environment_TextField.getText();
                String language = Language_TextField.getText();

                String updateQuery = "update summarydetails set domain = '" + domain + "', subDomain= '" + subDomain + "', project= '" + project + "', type= '" + type + "', environment= '" + environment + "', Language= '" + language + "'";

                statement = con.createStatement();

                statement.executeUpdate(updateQuery);

                this.showSummaryTableData();

                lMessageSummary.setText("Data updated successfully");
            }
        } catch (Exception e) {
            lMessageSummary.setText("Somthing went wrong while updating table data");
        } finally {
            try {
                con.close();
                prepareStatement.close();
            } catch (Exception e) {

            }
        }

    }//GEN-LAST:event_UpdateSummaryBtnActionPerformed

    private void UpdateModuleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateModuleBtnActionPerformed
        try {
            lMessageModule.setText("");
            DefaultTableModel model = (DefaultTableModel) Module_Table.getModel();
            if (Module_Table.getSelectedRow() == -1) {
                if (Module_Table.getRowCount() == 0) {
                    lMessageModule.setText("Table is empty");
                } else {
                    lMessageModule.setText("You must select a record");
                }
            } else {

                con = MySQLConnection.getConnection();

                String moduleno = ModuleNo_TextField.getText();
                String moduleName = ModuleName_TextField.getText();

                String updateQuery = "update moduledetails set ModuleNo = '" + moduleno + "' ,moduleName= '" + moduleName + "' where ModuleNo= '" + moduleno + "'";

                statement = con.createStatement();

                statement.executeUpdate(updateQuery);

                this.showModuleTableData();

                lMessageModule.setText("Data updated successfully");
            }
        } catch (Exception e) {
            lMessageModule.setText("Somthing went wrong while updating table data");
        } finally {
            try {
                con.close();
                prepareStatement.close();
            } catch (Exception e) {

            }
        }

    }//GEN-LAST:event_UpdateModuleBtnActionPerformed

    private void Module_TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Module_TableMouseClicked
        DefaultTableModel model = (DefaultTableModel) Module_Table.getModel();
        ModuleNo_TextField.setText(model.getValueAt(Module_Table.getSelectedRow(), 0).toString());
        ModuleName_TextField.setText(model.getValueAt(Module_Table.getSelectedRow(), 1).toString());

    }//GEN-LAST:event_Module_TableMouseClicked

    private void DeleteModuleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteModuleBtnActionPerformed
        try {
            lMessageModule.setText("");
            DefaultTableModel model = (DefaultTableModel) Module_Table.getModel();
            if (Module_Table.getSelectedRow() == -1) {
                if (Module_Table.getRowCount() == 0) {
                    lMessageModule.setText("Table is empty");
                } else {
                    lMessageModule.setText("You must select a record");
                }
            } else {
                con = MySQLConnection.getConnection();

                int row = Module_Table.getSelectedRow();
                String value = Module_Table.getModel().getValueAt(row, 0).toString();

                String deleteQuery = "delete from moduledetails where ModuleNo = '" + value + "'";

                prepareStatement = con.prepareStatement(deleteQuery);

                prepareStatement.executeUpdate();

                this.showModuleTableData();

                lMessageModule.setText("Deteted " + value + " successfully");

            }
        } catch (SQLException ex) {
            lMessageModule.setText("Somthing went wrong while deleting the data from the table");
        } catch (Exception ex) {
            Logger.getLogger(TestSuite.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                con.close();
                prepareStatement.close();
            } catch (Exception e) {

            }
        }

    }//GEN-LAST:event_DeleteModuleBtnActionPerformed

    public void showSummaryTableData() {
        try {
            con = MySQLConnection.getConnection();
            String query = "select * from summarydetails";
            prepareStatement = con.prepareStatement(query);
            resultSet = prepareStatement.executeQuery();
            Summary_Table.setModel(DbUtils.resultSetToTableModel(resultSet));
        } catch (Exception e) {
            System.out.println("Unable to featch Data from database");
            JOptionPane.showMessageDialog(null, "Unable to featch Data from database");
        } finally {
            try {
                con.close();
                prepareStatement.close();
                resultSet.close();
            } catch (Exception e) {

            }
        }
    }

    public void showModuleTableData() {
        try {
            con = MySQLConnection.getConnection();
            String query = "select * from moduledetails";
            prepareStatement = con.prepareStatement(query);
            resultSet = prepareStatement.executeQuery();
            Module_Table.setModel(DbUtils.resultSetToTableModel(resultSet));
        } catch (Exception e) {
            System.out.println("Unable to featch Data from database");
            JOptionPane.showMessageDialog(null, "Unable to featch Data from database");
        } finally {
            try {
                con.close();
                prepareStatement.close();
                resultSet.close();
            } catch (Exception e) {

            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddConfigBtn;
    private javax.swing.JButton AddModuleBtn;
    private javax.swing.JButton AddSummaryBtn;
    private javax.swing.JTextField AppName_TextField;
    private javax.swing.JComboBox<String> Browser_ComboBox;
    private javax.swing.JButton ClearConfigBtn;
    private javax.swing.JButton ClearSummaryBtn;
    private javax.swing.JTable Config_Table;
    private javax.swing.JButton DeleteModuleBtn;
    private javax.swing.JTextField Domain_TextField;
    private javax.swing.JTextField Environment_TextField;
    private javax.swing.JTextField FailRunIteration_TextField;
    private javax.swing.JButton HomeConfigBtn;
    private javax.swing.JComboBox<String> Language_ComboBox;
    private javax.swing.JTextField Language_TextField;
    private javax.swing.JTextField ModuleName_TextField;
    private javax.swing.JTextField ModuleNo_TextField;
    private javax.swing.JTable Module_Table;
    private javax.swing.JTextField Project_TextField;
    private javax.swing.JButton SignOutConfigBtn;
    private javax.swing.JTextField SubDomain_TextField;
    private javax.swing.JTable Summary_Table;
    private javax.swing.JTextField Type_TextField;
    private javax.swing.JButton UpdateConfigBtn;
    private javax.swing.JButton UpdateModuleBtn;
    private javax.swing.JButton UpdateSummaryBtn;
    private javax.swing.JComboBox<String> authenticationWindowPresent_ComboBox;
    private javax.swing.JTextField authenticationWindow_TextField;
    private javax.swing.JComboBox<String> dbConnectionFlag_ComboBox;
    private javax.swing.JTextField dbDriver_TextField;
    private javax.swing.JTextField dbHost_TextField;
    private javax.swing.JPasswordField dbPassword_TextField;
    private javax.swing.JTextField dbUser;
    private javax.swing.JComboBox<String> inputMethod_ComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lMessageModule;
    private javax.swing.JLabel lMessageSummary;
    private javax.swing.JTextField noOfTestData_TextField;
    private javax.swing.JTextField url_TextField;
    private javax.swing.JTextField waitTime_TextField;
    // End of variables declaration//GEN-END:variables
}
