/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package applicationconfiguration;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author home
 */
public class TestManual extends javax.swing.JFrame {

    Connection con = null;
    ResultSet resultSet = null;
    PreparedStatement prepareStatement = null;
    Statement statement;

    /**
     * Creates new form TestManual
     */
    public TestManual() throws Exception {
        initComponents();
        this.showTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Add_btn = new javax.swing.JButton();
        Update_btn = new javax.swing.JButton();
        Delete_btn = new javax.swing.JButton();
        Clear_btn = new javax.swing.JButton();
        Refersh_btn = new javax.swing.JButton();
        Back_btn = new javax.swing.JButton();
        SignOut_btn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lMessage = new javax.swing.JLabel();
        TestCaseName_Txt = new javax.swing.JTextField();
        Username_Txt = new javax.swing.JTextField();
        Password_Txt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TestManualData_Table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Commands", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 18), new java.awt.Color(0, 0, 153))); // NOI18N

        Add_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demoapplication/img/Button-Add-icon.png"))); // NOI18N
        Add_btn.setText("Add");
        Add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_btnActionPerformed(evt);
            }
        });

        Update_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demoapplication/img/Files-Edit-file-icon (1).png"))); // NOI18N
        Update_btn.setText("Update");
        Update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_btnActionPerformed(evt);
            }
        });

        Delete_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demoapplication/img/bin-2-icon.png"))); // NOI18N
        Delete_btn.setText("Delete");
        Delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_btnActionPerformed(evt);
            }
        });

        Clear_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demoapplication/img/Actions-edit-clear-icon (1).png"))); // NOI18N
        Clear_btn.setText("Clear");
        Clear_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Clear_btnActionPerformed(evt);
            }
        });

        Refersh_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demoapplication/img/Button-Refresh-icon (1).png"))); // NOI18N
        Refersh_btn.setText("Refresh");
        Refersh_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Refersh_btnActionPerformed(evt);
            }
        });

        Back_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demoapplication/img/home.png"))); // NOI18N
        Back_btn.setText("Home");
        Back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_btnActionPerformed(evt);
            }
        });

        SignOut_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demoapplication/img/SignOut-icon.png"))); // NOI18N
        SignOut_btn.setText("SignOut");
        SignOut_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignOut_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SignOut_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Refersh_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Back_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Clear_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Delete_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Update_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Add_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(Add_btn)
                .addGap(18, 18, 18)
                .addComponent(Update_btn)
                .addGap(18, 18, 18)
                .addComponent(Delete_btn)
                .addGap(18, 18, 18)
                .addComponent(Clear_btn)
                .addGap(18, 18, 18)
                .addComponent(Refersh_btn)
                .addGap(18, 18, 18)
                .addComponent(Back_btn)
                .addGap(18, 18, 18)
                .addComponent(SignOut_btn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TestData", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 18), new java.awt.Color(0, 0, 153))); // NOI18N

        jLabel1.setText("Test Case:");

        jLabel2.setText("Password:");

        jLabel3.setText("Username:");

        lMessage.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lMessage.setForeground(new java.awt.Color(204, 0, 0));

        Password_Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Password_TxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(TestCaseName_Txt))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Username_Txt)
                            .addComponent(Password_Txt))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TestCaseName_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Username_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Password_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );

        TestManualData_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TestCase", "Username", "Password"
            }
        ));
        TestManualData_Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TestManualData_TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TestManualData_Table);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1269, 505));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void addUserIntoDatabase() {
        try {
            con = MySQLConnection.getConnection();

            //Write a query to insert data into database
            String insertData = "insert into testdata_manual(TestCaseName,Username,Password) values(?,?,?)";

            prepareStatement = con.prepareStatement(insertData);
            prepareStatement.setString(1, TestCaseName_Txt.getText());
            prepareStatement.setString(2, Username_Txt.getText());
            prepareStatement.setString(3, Password_Txt.getText());
            if (!TestCaseName_Txt.getText().equals("")) {
                prepareStatement.execute();
                lMessage.setText("Data saved successfully");
            } else {
                JOptionPane.showMessageDialog(null, "insufficent informations");
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        } finally {
            try {
                con.close();
                prepareStatement.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Unable to close connection");
            }
        }
    }

    public void showTableData() throws Exception {
        try {
            con = MySQLConnection.getConnection();
            String query = "select * from testdata_manual";
            prepareStatement = con.prepareStatement(query);
            resultSet = prepareStatement.executeQuery();
            TestManualData_Table.setModel(DbUtils.resultSetToTableModel(resultSet));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } finally {
            try {
                con.close();
                prepareStatement.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Unable to close connection");

            } finally {
                try {
                    con.close();
                    prepareStatement.close();
                    resultSet.close();
                } catch (Exception e) {

                }
            }
        }
    }


    private void Add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_btnActionPerformed
        try {
            this.addUserIntoDatabase();
            this.showTableData();
        } catch (Exception e) {
            lMessage.setText("Somthing went wrong while adding table data");
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_Add_btnActionPerformed

    private void Password_TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Password_TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Password_TxtActionPerformed

    private void Update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_btnActionPerformed

        try {
            lMessage.setText("");
            DefaultTableModel model = (DefaultTableModel) TestManualData_Table.getModel();
            if (TestManualData_Table.getSelectedRow() == -1) {
                if (TestManualData_Table.getRowCount() == 0) {
                    lMessage.setText("Table is empty");
                } else {
                    lMessage.setText("You must select a record");
                }
            } else {

                con = MySQLConnection.getConnection();

                String tc_name = TestCaseName_Txt.getText();
                String u_name = Username_Txt.getText();
                String password = Password_Txt.getText();

                String updateQuery = "update testdata_manual set TestCaseName = '" + tc_name + "', Username ='" + u_name + "' ,Password= '" + password + "' where TestCaseName= '" + tc_name + "'";

                statement = con.createStatement();

                statement.executeUpdate(updateQuery);

                this.showTableData();

                lMessage.setText("Data updated successfully");
            }
        } catch (Exception e) {
            lMessage.setText("Somthing went wrong while updating table data");
            JOptionPane.showMessageDialog(null, e);
        } finally {
            try {
                con.close();
                prepareStatement.close();
                resultSet.close();
            } catch (Exception e) {

            }
        }
    }//GEN-LAST:event_Update_btnActionPerformed

    private void Back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_btnActionPerformed
        try {
            close();
            new HomePage().setVisible(true);
        } catch (Exception e) {

        }
    }//GEN-LAST:event_Back_btnActionPerformed

    private void Refersh_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Refersh_btnActionPerformed
        try {

            this.showTableData();
            lMessage.setText("");
            JOptionPane.showMessageDialog(null, "Table data refreshed successfully");
        } catch (Exception ex) {
            Logger.getLogger(TestSuite.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Refersh_btnActionPerformed

    private void SignOut_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignOut_btnActionPerformed
        try {
            close();
            new login().setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Couldn't sign out :(");
        }
    }//GEN-LAST:event_SignOut_btnActionPerformed

    private void Clear_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Clear_btnActionPerformed
        TestCaseName_Txt.setText("");
        Username_Txt.setText("");
        Password_Txt.setText("");
    }//GEN-LAST:event_Clear_btnActionPerformed

    private void Delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_btnActionPerformed
        try {
            lMessage.setText("");
            DefaultTableModel model = (DefaultTableModel) TestManualData_Table.getModel();
            if (TestManualData_Table.getSelectedRow() == -1) {
                if (TestManualData_Table.getRowCount() == 0) {
                    lMessage.setText("Table is empty");
                } else {
                    lMessage.setText("You must select a record");
                }
            } else {
                con = MySQLConnection.getConnection();
                int row = TestManualData_Table.getSelectedRow();
                String value = TestManualData_Table.getModel().getValueAt(row, 0).toString();

                String deleteQuery = "delete from testdata_manual where TestCaseName = '" + value + "'";

                prepareStatement = con.prepareStatement(deleteQuery);

                prepareStatement.executeUpdate();

                this.showTableData();

                lMessage.setText("Deteted " + value + " successfully");

            }
        } catch (SQLException ex) {
            lMessage.setText("Somthing went wrong while deleting the data from the table");
            JOptionPane.showMessageDialog(null, ex);
        } catch (Exception ex) {
            Logger.getLogger(TestSuite.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                con.close();
                prepareStatement.close();
                resultSet.close();
            } catch (Exception e) {

            }
        }
    }//GEN-LAST:event_Delete_btnActionPerformed

    private void TestManualData_TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TestManualData_TableMouseClicked
        DefaultTableModel model = (DefaultTableModel) TestManualData_Table.getModel();
        TestCaseName_Txt.setText(model.getValueAt(TestManualData_Table.getSelectedRow(), 0).toString());
        Username_Txt.setText(model.getValueAt(TestManualData_Table.getSelectedRow(), 1).toString());
        Password_Txt.setText(model.getValueAt(TestManualData_Table.getSelectedRow(), 2).toString());
    }//GEN-LAST:event_TestManualData_TableMouseClicked
    public void close() {

        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_btn;
    private javax.swing.JButton Back_btn;
    private javax.swing.JButton Clear_btn;
    private javax.swing.JButton Delete_btn;
    private javax.swing.JTextField Password_Txt;
    private javax.swing.JButton Refersh_btn;
    private javax.swing.JButton SignOut_btn;
    private javax.swing.JTextField TestCaseName_Txt;
    private javax.swing.JTable TestManualData_Table;
    private javax.swing.JButton Update_btn;
    private javax.swing.JTextField Username_Txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lMessage;
    // End of variables declaration//GEN-END:variables
}
